import { FileText, Trash2 } from 'lucide-react'
import BoxRenderer from '../boxes/BoxRenderer'
import ExpandedBox from '../boxes/ExpandedBox'

import { useState } from 'react'

export default function Workspace({ document, selectedBoxId, onAddBox, onSelectBox, onUpdateBox, onUpdateLayout, onChangeZoom, onCopyBox, onDeleteBox, onDeleteAll, onUploadImage, onRemoveImage }) {
  const [expandedId, setExpandedId] = useState(null)
  const [confirmingDeleteAll, setConfirmingDeleteAll] = useState(false)
  const expandedBox = document.boxes.find((box) => box.id === expandedId)
  const performDeleteAll = () => { onDeleteAll(); setConfirmingDeleteAll(false) }
  return <section className="workspace" aria-label="Visual document canvas"><div className="workspace-toolbar" aria-label="Canvas controls"><span className="document-label">{document.title}</span><div className="workspace-actions"><span className="zoom-label">Single page · 100%</span>{document.boxes.length > 0 && <button className="delete-all-button" type="button" onClick={() => setConfirmingDeleteAll(true)}><Trash2 size={13} />Delete all</button>}</div></div><div className="canvas-viewport"><div className="canvas" role="region" aria-label="Document canvas" onPointerDown={() => onSelectBox(null)}>{document.boxes.map((box) => <BoxRenderer key={box.id} box={box} selected={selectedBoxId === box.id} onSelect={() => onSelectBox(box.id)} onChange={(content, metadata) => onUpdateBox(box.id, content, metadata)} onUpload={(file) => onUploadImage(box.id, file)} onRemove={() => onRemoveImage(box.id)} onUpdateLayout={(changes) => onUpdateLayout(box.id, changes)} onZoomIn={() => onChangeZoom(box.id, 1)} onZoomOut={() => onChangeZoom(box.id, -1)} onExpand={() => setExpandedId(box.id)} onCopy={() => onCopyBox(box.id)} onDelete={() => onDeleteBox(box.id)} />)}{document.boxes.length === 0 && <div className="empty-state"><div className="empty-icon"><FileText size={22} strokeWidth={1.6} /></div><h1>Start with a thought</h1><p>Add a box to begin shaping your visual document.</p><button className="button button-primary" type="button" onPointerDown={(event) => event.stopPropagation()} onClick={() => onAddBox('text')}>Create a text box</button></div>}</div></div>{expandedBox && <ExpandedBox box={expandedBox} onChange={(content, metadata) => onUpdateBox(expandedBox.id, content, metadata)} onClose={() => setExpandedId(null)} />}{confirmingDeleteAll && <div className="confirm-backdrop" role="presentation"><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-all-title"><h2 id="delete-all-title">Delete all boxes?</h2><p>This will remove all content from the current page.</p><div><button className="button button-quiet" type="button" onClick={() => setConfirmingDeleteAll(false)}>Cancel</button><button className="button delete-all-confirm" type="button" onClick={performDeleteAll}>Delete All</button></div></section></div>}</section>
}
