import { useState } from 'react'
import { Braces, ChevronDown, FileDown, FilePlus2, FileText, FolderOpen, Image, Moon, Plus, Save, Sun, TerminalSquare, Video } from 'lucide-react'
import IconButton from '../ui/IconButton'

const addOptions = [{ type: 'text', label: 'Text', icon: FileText }, { type: 'image', label: 'Image', icon: Image }, { type: 'video', label: 'Video', icon: Video }, { type: 'code', label: 'Code', icon: Braces }, { type: 'output', label: 'Output', icon: TerminalSquare }]

export default function Header({ theme, saveStatus, exportStatus, onThemeToggle, onAddBox, onNewDocument, onOpenDocuments, onExport }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const [exportOpen, setExportOpen] = useState(false)
  return <header className="app-header">
    <div className="header-brand" aria-label="present.now home"><span className="brand-mark" aria-hidden="true"><span /></span><span className="brand-name">present<span>.now</span></span></div>
    <div className="header-actions"><button className="button button-quiet" type="button" onClick={onNewDocument}><FilePlus2 size={16} /><span>New</span></button><button className="button button-quiet documents-button" type="button" onClick={onOpenDocuments}><FolderOpen size={16} /><span>Documents</span></button><div className="add-box-menu"><button className="button button-primary" type="button" aria-expanded={menuOpen} aria-haspopup="menu" onClick={() => setMenuOpen((open) => !open)}><Plus size={16} /><span>Add box</span><ChevronDown size={14} /></button>{menuOpen && <div className="add-menu-popover" role="menu">{addOptions.map(({ type, label, icon: Icon }) => <button type="button" role="menuitem" key={type} onClick={() => { onAddBox(type); setMenuOpen(false) }}><Icon size={16} /><span>{label}</span></button>)}</div>}</div></div>
    <div className="header-tools"><span className={`save-status ${(saveStatus === 'Unable to save locally' || exportStatus.startsWith('Unable')) ? 'save-error' : ''}`} title="Changes are stored only in your browser" role="status" aria-live="polite"><Save size={14} /><span>{exportStatus || saveStatus}</span></span><IconButton label={theme === 'dark' ? 'Use light theme' : 'Use dark theme'} onClick={onThemeToggle}>{theme === 'dark' ? <Sun size={17} /> : <Moon size={17} />}</IconButton><div className="add-box-menu export-menu"><button className="button button-quiet export-button" type="button" aria-label="Export document" aria-haspopup="menu" aria-expanded={exportOpen} onClick={() => setExportOpen((open) => !open)}><FileDown size={16} /><span>Export</span><ChevronDown size={15} /></button>{exportOpen && <div className="add-menu-popover export-popover" role="menu" aria-label="Export document"><button type="button" role="menuitem" onClick={() => { onExport('pdf'); setExportOpen(false) }}>Export as PDF</button><button type="button" role="menuitem" onClick={() => { onExport('pptx'); setExportOpen(false) }}>Export as PPTX</button><button type="button" role="menuitem" onClick={() => { onExport('docx'); setExportOpen(false) }}>Export as DOCX</button></div>}</div></div>
  </header>
}
